name: saryacademy
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  google_fonts_arabic: ^1.1.7
  provider: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sary-logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/landingScreen/
    - assets/images/profile/
    - assets/images/home/
    - assets/images/gallery/
    - assets/images/PR/
    - assets/images/events/

  fonts:
    - family: arialBold
      fonts:
        - asset: assets/fonts/arial-bold.ttf

    - family: arial
      fonts:
        - asset: assets/fonts/arial.ttf

    - family: arialRounded
      fonts:
        - asset: assets/fonts/Arial-Rounded-MT-Bold.ttf
