name: saryacademy
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: null
  change_app_package_name: ^1.0.0
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  date_format: ^2.0.4
  datetime_picker_formfield: null
  file_picker: null
  firebase_auth: null
  firebase_core: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_datetime_picker: 1.5.1
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: null
  flutter_locales: null
  flutter_pdfview: ^1.2.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  modal_progress_hud: ^0.1.3
  open_file: ^3.2.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: null
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sary-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/landingScreen/
    - assets/images/profile/
    - assets/images/home/
    - assets/images/gallery/
    - assets/images/PR/
    - assets/images/events/
    - assets/images/
    - assets/images/flags/
    - assets/locales/en.json
    - assets/locales/ar.json

  fonts:
    - family: arialBold
      fonts:
        - asset: assets/fonts/arial-bold.ttf

    - family: arial
      fonts:
        - asset: assets/fonts/arial.ttf

    - family: almarai
      fonts:
        - asset: assets/fonts/Almarai.ttf

    - family: arialRounded
      fonts:
        - asset: assets/fonts/Arial-Rounded-MT-Bold.ttf
